all : run

# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
GTEST_DIR = ./test/googletest

# Where to find user code.
TEST_DIR = ./test
SRC_DIR = ./src

# Rapid Check path
RAPIDCHECK_DIR = ./test/rapidcheck

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST_DIR)/include -std=c++11

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -pthread 

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# Builds gtest.a and gtest_main.a.

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized.  This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

EQUIP = Equipment.o Body.o Helm.o Pants.o Shield.o Weapon.o

run : build
	./RPG

build : $(SRC_DIR)/main.cpp Creature.o Player.o Monster.o $(EQUIP) Dungeon.o World.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o RPG $^

test : unit_tests
	./unit_tests

clean : 
	rm -f gtest.a gtest_main.a *.o RPG unit_tests

# Equipment
Equipment.o : $(SRC_DIR)/Equipment.cpp $(SRC_DIR)/headers/Equipment.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Equipment.cpp

# Other Equipment
Body.o : $(SRC_DIR)/Body.cpp $(SRC_DIR)/headers/Body.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Body.cpp

Helm.o : $(SRC_DIR)/Helm.cpp $(SRC_DIR)/headers/Helm.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Helm.cpp

Pants.o : $(SRC_DIR)/Pants.cpp $(SRC_DIR)/headers/Pants.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Pants.cpp

Shield.o : $(SRC_DIR)/Shield.cpp $(SRC_DIR)/headers/Shield.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Shield.cpp

Weapon.o : $(SRC_DIR)/Weapon.cpp $(SRC_DIR)/headers/Weapon.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Weapon.cpp

#Creature
Creature.o : $(SRC_DIR)/Creature.cpp $(SRC_DIR)/headers/Creature.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Creature.cpp

# Monster
Monster.o : $(SRC_DIR)/Monster.cpp $(SRC_DIR)/headers/Monster.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Monster.cpp

# Player
Player.o : $(SRC_DIR)/Player.cpp $(SRC_DIR)/headers/Player.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Player.cpp

# Dungeon
Dungeon.o : $(SRC_DIR)/Dungeon.cpp $(SRC_DIR)/headers/Dungeon.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/Dungeon.cpp

# World
World.o : $(SRC_DIR)/World.cpp $(SRC_DIR)/headers/World.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/World.cpp
	

# Tests
Equipment_unittest.o : $(TEST_DIR)/Equipment_unittest.cpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(TEST_DIR)/Equipment_unittest.cpp

Creature_unittest.o : $(TEST_DIR)/Creature_unittest.cpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(TEST_DIR)/Creature_unittest.cpp

Player_unittest.o : $(TEST_DIR)/Player_unittest.cpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(TEST_DIR)/Player_unittest.cpp

Monster_Generation.o : $(TEST_DIR)/Monster_Generation.cpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(TEST_DIR)/Monster_Generation.cpp

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = Equipment_unittest.o Player_unittest.o Creature_unittest.o Monster_Generation.o

unit_tests : $(EQUIP) Creature.o Player.o Monster.o $(TESTS) gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@
